[package]
name = "eigenda-cert"
version = "0.1.0"
edition = "2021"

[features]
rkyv = ["dep:rkyv", "alloy-primitives/rkyv"]
bytecheck = ["rkyv", "rkyv/bytecheck"]

[dependencies]
alloy-primitives = { workspace = true, features = ["rlp", "serde"] }
alloy-rlp = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
canoe-bindings = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
rkyv = { workspace = true, optional = true }
